### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by Reem-lab** [andres-condezo/Leaderboard#3]
## Highlights to say 👍 
 - Your project looks very good
 - You made good practices in your code 💯
 - No issues to say

<img src="https://media2.giphy.com/media/kdQuvu0LtCEjxYgTcS/giphy.gif"/>

**Comment by hendridg** [comment]
## Hi @andres-condezo :fire: 

- Very nice project :+1: 
- Correct Gitflow :100: 
- No issues to said :1st_place_medal: 

### Keep coding :computer: , keep working :mechanical_arm:
